import { afterEach, expect, test } from 'bun:test';
import { createMockScenario, MOCK_SESSION_IDS } from './scenario.js';

afterEach(() => {
	delete process.env.TURIN_MOCK_MESSAGE_COUNT;
	delete process.env.TURIN_MOCK_STREAM;
});

test('large transcripts are generated by index instead of materialized', () => {
	process.env.TURIN_MOCK_MESSAGE_COUNT = '1000000';
	const scenario = createMockScenario();
	expect(scenario.messageCount(MOCK_SESSION_IDS.long)).toBe(1_000_000);
	expect(scenario.messageAt(MOCK_SESSION_IDS.long, 999_999).id).toBe(`${MOCK_SESSION_IDS.long}-message-1000000`);
	expect(scenario.sessions).toHaveLength(13);
});

test('stream behavior is selected independently of response content', () => {
	process.env.TURIN_MOCK_STREAM = 'interrupt';
	const response = createMockScenario().responseFor('Inspect the stream');
	expect(response.mode).toBe('interrupt');
	expect(response.text).toContain('Inspect the stream');
});

test('linked sessions carry resolvable parent context and stay out of the root set', () => {
	const scenario = createMockScenario();
	const roots = scenario.sessions.filter((session) => !session.parent_session_id);
	const linked = scenario.sessions.filter((session) => session.parent_session_id);

	expect(roots).toHaveLength(10);
	expect(linked).toHaveLength(3);
	for (const session of linked) {
		const parent = scenario.sessions.find((candidate) => candidate.id === session.parent_session_id);
		expect(parent).toBeDefined();
		expect(session.parent_title).toBe(parent?.title);
		expect(session.origin_turn_id).toBeTruthy();
	}
});

test('long transcripts exercise rich response surfaces', () => {
	const scenario = createMockScenario();
	const orderedList = scenario.messageAt(MOCK_SESSION_IDS.long, 1);
	const table = scenario.messageAt(MOCK_SESSION_IDS.long, 3);
	const reasoning = scenario.messageAt(MOCK_SESSION_IDS.long, 7);
	const tool = scenario.messageAt(MOCK_SESSION_IDS.long, 11);
	const responseAfterTool = scenario.messageAt(MOCK_SESSION_IDS.long, 12);

	expect(orderedList.content).toContain('1. Verify');
	expect(table.content).toContain('| Concern |');
	expect(reasoning.reasoning?.duration_ms).toBeGreaterThan(0);
	expect(reasoning.metrics?.input_tokens).toBeGreaterThan(0);
	expect(tool.role).toBe('tool');
	expect(responseAfterTool.role).toBe('assistant');
});
