import { afterEach, expect, test } from 'bun:test';
import { createMockScenario } from './scenario.js';

afterEach(() => {
	delete process.env.TURIN_MOCK_MESSAGE_COUNT;
	delete process.env.TURIN_MOCK_STREAM;
});

test('large transcripts are generated by index instead of materialized', () => {
	process.env.TURIN_MOCK_MESSAGE_COUNT = '1000000';
	const scenario = createMockScenario();
	expect(scenario.messageCount('session-long')).toBe(1_000_000);
	expect(scenario.messageAt('session-long', 999_999).id).toBe('session-long-message-1000000');
	expect(scenario.sessions).toHaveLength(3);
});

test('stream behavior is selected independently of response content', () => {
	process.env.TURIN_MOCK_STREAM = 'interrupt';
	const response = createMockScenario().responseFor('Inspect the stream');
	expect(response.mode).toBe('interrupt');
	expect(response.text).toContain('Inspect the stream');
});
