[package]
name = "turin-control-client"
version = "0.27.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", default-features = false, features = ["fs"] }
turin-channel-core = { path = "../turin-channel-core" }
turin-daemon-client = { path = "../turin-daemon-client" }
turin-daemon-protocol = { path = "../turin-daemon-protocol" }
turin-remote-client = { path = "../turin-remote-client" }
turin-types = { path = "../turin-types" }

[dev-dependencies]
tempfile = "3.10"
tokio = { version = "1.0", default-features = false, features = ["macros", "rt-multi-thread"] }
turin = { path = "../.." }
